### PR TITLE
Fix bug: null events at the beginning and add option to process one event at a time

### PR DESCRIPTION
**Pull request by wkliao**
A quick update to try generating graphs one event at a time,
in case out-of-memory errors are encountered.

### CODE REVIEW

**Comment by vhewes** [comment]
how much of an impact will this change have on runtime? if this will slow down processing on HPC systems, i'd like to keep this change as an alternative option rather than replacing the default behaviour entirely

**Comment by wkliao** [comment]
I can run some tests to evaluate, if you or @cerati can provide me an input file.

**Comment by wkliao** [comment]
I think this PR is now ready to be merged.

**Review by vhewes — APPROVED** [review]
thanks!

**Comment by wkliao** [comment]
> how much of an impact will this change have on runtime? if this will slow down processing on HPC systems, i'd like to keep this change as an alternative option rather than replacing the default behaviour entirely

Just to answer this question to complete the PR.
No, it has no significant impact to the timing, as the events are already built one at a time.
The difference of this PR is the previous implementation built all events and saved the
results in memory and write them later, which can take more memory space.

**Pull request merged**
